### ISSUE TITLE
README.md out of date (11/05/2018)

### ISSUE THREAD

**Issue by climbfuji** [NCAR/NCEPlibs#1]
The latest addition of libraries needed for the regional pre-processing (https://github.com/climbfuji/NCEPlibs/pull/2) is not reflected in README.md. @mkavulich can you take care of adding your new options (and update the 'last update' line) when you get the chance, please?

**Comment by climbfuji** [comment]
Note that this is now in the NCAR repository, my fork will no longer be updated.

**Comment by zemega** [comment]
If the netcdf location was not specified, the make_ncep_libs.sh askes for NETCDF_LIB and NETCDF_INC. Specifically "ERROR: You must define the locations of NETCDF library (NETCDF_LIB) and include (NETCDF_INC) files to compile upp libraries". This is misleading. What user needs to define is the location of NETCDF. NETCDF_LIB and NETCDF_INC are derived from user input NETCDF.

I have defined the location of NETCDF_INC and NETCDF_LIB separately, but make_ncep_libs.sh could not find them. When I define NETCDF, the make_ncep_libs.sh can find them.

**Comment by zemega** [comment]
The make_ncep_libs.sh also asked for JASPER_INC and PNG_INC.
