### ISSUE TITLE
NCEPlibs can't be compile with gfortran 9.3.0

### ISSUE THREAD

**Issue by zemega** [NCAR/NCEPlibs#15]
Hello. 
I'm using Ubuntu 20.04 under WSL inside Windows 10. I'm using gfortran 9.3.0 and gcc 9.3.0. Running the command ./make_ncep_libs.sh -s linux -c gnu -d /home/yunus/WRF/NCEPLIBS -o 0 -m 1 -a upp will have the following error. I have attached the logfile for the make process. It seems that the function iand has been changed in at least gfortran 9.2++.

[log.txt](https://github.com/NCAR/NCEPlibs/files/4951349/log.txt)

``intmath.f:207:14:

  207 |       if(iand(i,i-1)/=0) then
      |              1
Error: Arguments of ‘iand’ have different kind type parameters at (1)
intmath.f:172:14:

  172 |       if(iand(i,i-1)/=0) then
      |              1
Error: Arguments of ‘iand’ have different kind type parameters at (1)
make[1]: *** [makefile:108: ../../../../libg2_v3.1.0_4.a(intmath.o)] Error 1
make[1]: Leaving directory '/mnt/c/WRF/Source-Code/NCEPlibs-master/exec_linux.gnu/src/g2/v3.1.0/src'
make: *** [Makefile:38: upplibs] Error 2

An error occurred building the NCEP libraries``

**Comment by Quba1** [comment]
Was that issue resolved or is there maybe an alternative solution?
I am using gcc 9.2.0 and I have the same problem, and I can't change the version of the compiler.

**Comment by climbfuji** [comment]
All, this version of NCEPLIBS is actually abandoned - we should either delete the fork or at least mark it as no longer in use. 

We have moved to https://github.com/NOAA-EMC/NCEPLIBS and https://github.com/NOAA-EMC/NCEPLIBS-external for prerequisites (including detailed installation notes). Depending on what you want to use the libraries for, you could try the latest "develop" branches of both (obviously start with NCEPLIBS-external and read the wiki and README.txt), or the release tags ufs-v1.1.0 (for the upcoming UFS Medium-Range Weather Application release 1.1) or the release/public-v2 (for the November release of the UFS Short-Range Weather Application; note: currently in testing).

**Comment by zemega** [comment]
Hello. 

Can the front page, that is https://github.com/NCAR/NCEPlibs be updated to state this fork is no longer in use and be pointed at the right one?

If I'm not wrong, when I opened the issue, I was trying to build UPP which the requirement of requirement was NCEPlibs. The official documentation at https://dtcenter.org/community-code/unified-post-processor-upp/upp-user-release-version-4-1-0, and the pdf file https://dtcenter.org/sites/default/files/community-code/upp-users-guide-v4.1.pdf states that 

> Note:These are specific versions of the NCEP libraries maintained by NCAR/DTC and other versions of NCEPlibs may not work.

I believe if the UPP documentation is not updated, more user will be directed to this git.

**Comment by climbfuji** [comment]
> Hello.
> 
> Can the front page, that is https://github.com/NCAR/NCEPlibs be updated to state this fork is no longer in use and be pointed at the right one?
> 
> If I'm not wrong, when I opened the issue, I was trying to build UPP which the requirement of requirement was NCEPlibs. The official documentation at https://dtcenter.org/community-code/unified-post-processor-upp/upp-user-release-version-4-1-0, and the pdf file https://dtcenter.org/sites/default/files/community-code/upp-users-guide-v4.1.pdf states that
> 
> > Note:These are specific versions of the NCEP libraries maintained by NCAR/DTC and other versions of NCEPlibs may not work.
> 
> I believe if the UPP documentation is not updated, more user will be directed to this git.

I am adding @mkavulich here, because he is the "new" owner of the NCAR NCEPLIBS repo which, you are correct, was meant to be a specific version for supporting UPP for a while (while the UFS applications have moved on to the URLs I mentioned beforehand). I hope @mkavulich can update us about whether the NCAR NCEPLIBS are still meant to be used for UPP, or whether UPP has also moved on the the NOAA-supported NCEPLIBS. Apologies for the confusion that all this may have caused.
