### ISSUE TITLE
Error when install NCEPlibs on Ubuntu

### ISSUE THREAD

**Issue by hoanghuygn** [NCAR/NCEPlibs#17]
f951: Fatal Error: Reading module ‘nemsio_openclose’ at line 1667 column 7: Unexpected EOF
This is a my error when i install NCEPlibs by command: ./make_ncep_libs.sh -s linux -c gnu -d .../..../ -o 0 -a upp 
Please help me!

**Comment by climbfuji** [comment]
@hoanghuygn is there a particular reason to use this repository? The officially supported version for the ufs-weather-model is here: https://github.com/noaa-emc/nceplibs

@mkavulich maintains the NCAR fork, I don't know what its purpose is these days.

**Comment by zemega** [comment]
@climbfuji From this [UPP for WRF V 4.1](https://dtcenter.org/community-code/unified-post-processor-upp-wrf/upp-user-release-version-4-1-0) page, I assume this is the only latest UPP version that supports WRF. As it says 

> This will be the last supported version for WRF model data.

I have been searching for ways to post-process WRF output, and this page leads me to believe that only this UPP for WRF V4.1 would be able to process the output from WRF (preferably WRF 4.2). Is this not the case?

**Comment by climbfuji** [comment]
I am not the person to answer this question, sorry. It also doesn't fit to the topic of this issue. I would ask at the WRF user's forum if I were you, and you'll get the right answer.

**Comment by ghost** [comment]
> f951: Fatal Error: Reading module ‘nemsio_openclose’ at line 1667 column 7: Unexpected EOF
> 
> This is a my error when i install NCEPlibs by command: ./make_ncep_libs.sh -s linux -c gnu -d .../..../ -o 0 -a upp 
> 
> Please help me!

I have a script that installs the wrf and the nceplibs that might be helpful for you.

**Comment by climbfuji** [comment]
> > f951: Fatal Error: Reading module ‘nemsio_openclose’ at line 1667 column 7: Unexpected EOF
> > This is a my error when i install NCEPlibs by command: ./make_ncep_libs.sh -s linux -c gnu -d .../..../ -o 0 -a upp
> > Please help me!
> 
> I have a script that installs the wrf and the nceplibs that might be helpful for you.

Hi, please note that this repository is no longer actively maintained. For the latest public release of the NCEPLIBS (and prerequisites called NCEPLIBS-external), please see https://github.com/NOAA-EMC/NCEPLIBS-external and https://github.com/NOAA-EMC/NCEPLIBS. The repository https://github.com/NOAA-EMC/NCEPLIBS contains a wiki, a top-level README.md file, and a directory `doc` with detailed instructions on how all the libraries can be set up. Please make sure to choose tag `ufs-v2.0.0` to use the latest public release for both (the `develop` branches may not work).
